/******************************************************************************
*
* Copyright (C) Chaoyong Zhou
* Email: bgnvendor@gmail.com 
* QQ: 2796796
*
*******************************************************************************/
#ifndef _POLY_INC
#define _POLY_INC

#include "findex.inc"

FUNC_ADDR_NODE g_poly_func_addr_list[ ] = {
};

static UINT32 g_poly_func_addr_list_len = sizeof(g_poly_func_addr_list)/sizeof(g_poly_func_addr_list[0]);

#endif/*_POLY_INC*/
