/******************************************************************************
*
* Copyright (C) Chaoyong Zhou
* Email: bgnvendor@gmail.com 
* QQ: 2796796
*
*******************************************************************************/
#ifndef _POLYZ_INC
#define _POLYZ_INC

#include "findex.inc"

FUNC_ADDR_NODE g_polyz_func_addr_list[ ] = {
};

UINT32 g_polyz_func_addr_list_len = sizeof(g_polyz_func_addr_list)/sizeof(g_polyz_func_addr_list[0]);

#endif/*_POLYZ_INC*/
